import type { Metadata } from "next";
import { Lato   } from "next/font/google";
import "./globals.css";



const fontLato = Lato({
  variable: "--font-lato",
  subsets: ["latin"],
  weight: ["400","700"]
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fontLato.variable}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
